### ISSUE TITLE
Error When Using for SmartMatrix

### ISSUE THREAD

**Issue by PixelMan222** [pixelmatix/GifDecoder#8]
I'm trying to compile the code for AnimatedGifs from SmartMatrix and I have downloaded all the libraries I need, when I went to compile it gave me this error message

C:\Users\Ricky\Desktop\Arduino\libraries\GifDecodermaster\src/GifDecoder_Impl.h: In member function 'int GifDecoder<maxGifWidth, maxGifHeight, lzwMaxBits, useMalloc>::startDecoding(uint8_t*, int)':

C:\Users\Ricky\Desktop\Arduino\libraries\GifDecodermaster\src/GifDecoder_Impl.h:323:16: error: 'BIG_ENDIAN_PIXELS' was not declared in this scope

     gif->begin(BIG_ENDIAN_PIXELS, GIF_PALETTE_RGB888);

                ^

Error compiling for board Teensy 3.5.

The error comes from the file GifDecoder_Impl.h and I don't know how to fix it

**Comment by embedded-creations** [comment]
The AnimatedGIF Library was updated recently to version 1.4.0 with a new API and now isn't compatible with GifDecoder.  If you check out an earlier version of AnimatedGIF like 1.3.2 it should work.

**Comment by PixelMan222** [comment]
You're my hero

**Comment by embedded-creations** [comment]
This is fixed if you upgrade to the latest AnimatedGIF: 1.4.1
